### ISSUE TITLE
comment to ja version

### ISSUE THREAD

**Issue by atachibana** [jawordpressorg/Security-White-Paper#3]
- 「バージョン番号とセキュリティリリース」
  第2段落
  「メージャー」バージョン => 「メジャー」バージョン
- 「WordPress セキュリティチーム」
  第2段落
  ... 脆弱性を解決するなどように、=> 

この部分は全体として下のように並べ替えてはいかがでしょうか?

WordPress のセキュリティチームは、しばしば他のセキュリティチームと協力して、共通に依存するプログラムの問題に対処します。例えば、WordPress 3.9.2 での、WordPress に同梱の XML-RPC API によって使用されていた PHP XML パーサの脆弱性問題などです。この脆弱性の解決は、WordPress と Drupal のセキュリティチームの共同の努力の結果でした。
- 「WordPress のセキュリティリスク、プロセス、およびその歴史」
  第4段落
  「WordPress につて」の画面 -> 「WordPress について」の画面
- 「2013年の OWASP トップ10」
  第1段落
  組み合わにより -> 組み合わせにより
- 「A2 - 不完全な認証とセッション管理」
  第1段落
  WordPress のコアコアソフトウェアは、-> WordPress のコアソフトウェアは、
- 「A3 - クロスサイトスクリプティング (XSS)」
  第1段落
  様々な機能のを提供しています -> 様々な機能を提供しています
- 「HTTP API」
  第1段落
  リクエスを生成 -> リクエストを生成

**Comment by tekapo** [comment]
@atachibana さん、ありがとうございます!
修正をすべて頂きました。

**Comment by atachibana** [comment]
使っていただいてありがとうございます。
そして、翻訳お疲れ様です。他のチームと協力してる事実など初めて知ったことがたくさんあって勉強になりました。
