### ISSUE TITLE
翻訳者名クレジットについて

### ISSUE THREAD

**Issue by tekapo** [jawordpressorg/Security-White-Paper#5]
@naokomc さん、 @atachibana さん、@nukaga さん、

セキュリティ白書の翻訳のご協力をありがとうございました。

公開のアナウンスに翻訳者名のクレジットを入れたいと思うので、ご希望の表記(とTwitter、ブログ等のURL)をお知らせください。

**Comment by naokomc** [comment]
お疲れさまでした。以下でお願い致します。

表記: 高野直子
Twitter: @naokomc
URL: http://ja.naoko.cc

**Comment by atachibana** [comment]
ご配慮ありがとうございます。
以下でお願いします。
表記: 立花明
Twitter: @atachibana

**Comment by nukaga** [comment]
殆ど何もできていないのにお気遣いありがとうございます。
以下になります。

表記: 額賀順子
Twitter: @nukaga
URL: http://nuuno.net/

**Comment by tekapo** [comment]
@naokomc さん、 @atachibana さん、@nukaga さん、
ありがとうございます!
公開しました!
https://ja.wordpress.org/2015/12/01/wordpress-security-white-paper/
https://ja.wordpress.org/security/
